In [10]:
import pandas as pd

# 1. 데이터 확인
# 파일 경로 설정
filename = '../data/bccard_201906.csv'
df = pd.read_csv(filename)
df.head(3)

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52

In [24]:
# 1. 앞부분 확인 (기본 5행)
print("--- 데이터 앞부분 (head) ---")
display(df.head(3))

--- 데이터 앞부분 (head) ---

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52

In [25]:
# 2. 뒷부분 확인 (기본 5행)
print("\n--- 데이터 뒷부분 (tail) ---")
display(df.tail(3))

--- 데이터 뒷부분 (tail) ---

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
99998,99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

In [26]:
# 3. 데이터 수 확인
print(f"\n전체 데이터 행 수: {len(df)}개")
print(f"전체 데이터 열 수: {df.shape[1]}개")

전체 데이터 행 수: 100001개
전체 데이터 열 수: 24개

In [28]:
# 서울 거주 고객과 비거주 고객 분리
seoul_cust = df[df['CSTMR_MEGA_CTY_NM'] == '서울특별시']
non_seoul_cust = df[df['CSTMR_MEGA_CTY_NM'] != '서울특별시']

# 1. 서울 거주 고객 분석 테이블
seoul_table = pd.DataFrame({
    '구분': ['서울 거주 고객'],
    '고객수(데이터건수)': [len(seoul_cust)],
    '총 소비액(AMT)': [seoul_cust['AMT'].sum()],
    '총 카드이용건수(CNT)': [seoul_cust['CNT'].sum()]
})

# 2. 비거주 고객 분석 테이블
non_seoul_table = pd.DataFrame({
    '구분': ['비거주 고객'],
    '고객수(데이터건수)': [len(non_seoul_cust)],
    '총 소비액(AMT)': [non_seoul_cust['AMT'].sum()],
    '총 카드이용건수(CNT)': [non_seoul_cust['CNT'].sum()]
})

print("--- [표 1] 서울 거주 고객 분석 ---")
display(seoul_table)

print("\n--- [표 2] 비거주 고객 분석 ---")
display(non_seoul_table)

--- [표 1] 서울 거주 고객 분석 ---

         구분  고객수(데이터건수)    총 소비액(AMT)  총 카드이용건수(CNT)
0  서울 거주 고객       54150  119663142676        5542462

--- [표 2] 비거주 고객 분석 ---

       구분  고객수(데이터건수)    총 소비액(AMT)  총 카드이용건수(CNT)
0  비거주 고객       45851  146587135822        4950200

In [34]:
# 데이터 전처리: 업종명의 공백 제거 ('편 의 점' -> '편의점')
df['TP_BUZ_NM'] = df['TP_BUZ_NM'].str.replace(' ', '')

# 1. 전체 편의점 총 소비액
total_cvs_amt = df[df['TP_BUZ_NM'] == '편의점']['AMT'].sum()
print(f"1. 전국 편의점 총 소비액: {total_cvs_amt:,}원")

# 2. 강남구 전체 총 소비액 (가맹점 기준)
total_gangnam_amt = df[df['CTY_RGN_NM'] == '강남구']['AMT'].sum()
print(f"2. 강남구 지역 총 소비액: {total_gangnam_amt:,}원")

# 3. 강남구 소재 편의점 총 소비액
gangnam_cvs = df[(df['CTY_RGN_NM'] == '강남구') & (df['TP_BUZ_NM'] == '편의점')]
gangnam_cvs_amt = gangnam_cvs['AMT'].sum()
print(f"3. 강남구 내 편의점 총 소비액: {gangnam_cvs_amt:,}원")

# 4. 강남구 편의점 소비액 중 [강남구 거주자] vs [비거주자] 비교
# 'CSTMR_CTY_RGN_NM' 컬럼이 고객의 거주 구 정보를 담고 있습니다.
gn_res_amt = gangnam_cvs[gangnam_cvs['CSTMR_CTY_RGN_NM'] == '강남구']['AMT'].sum()
gn_non_res_amt = gangnam_cvs[gangnam_cvs['CSTMR_CTY_RGN_NM'] != '강남구']['AMT'].sum()

# 거주자/비거주자 소비액 차이 계산
amt_diff = gn_non_res_amt - gn_res_amt

# 결과 테이블 생성
comparison_table = pd.DataFrame({
    '구분': ['강남구 거주자', '강남구 비거주자', '액수 차이(비거주/거주)'],
    '강남구 편의점 소비액': [gn_res_amt, gn_non_res_amt, amt_diff]
})

print("\n--- [강남구 편의점] 거주자 vs 비거주자 소비 비교 ---")
display(comparison_table)

1. 전국 편의점 총 소비액: 7,299,184,098원
2. 강남구 지역 총 소비액: 35,535,648,502원
3. 강남구 내 편의점 총 소비액: 707,275,140원

--- [강남구 편의점] 거주자 vs 비거주자 소비 비교 ---

              구분  강남구 편의점 소비액
0        강남구 거주자    288379890
1       강남구 비거주자    418895250
2  액수 차이(비거주/거주)    130515360